### ISSUE TITLE
Fehler beim Einzaheln von Geld wenn kein Haupkonto Festgelegt ist

### ISSUE THREAD

**Issue by ProfPanda07** [Hydra-Roleplay/Issue-tracker#2]
## Beschreibe den Fehler
dass und das ist der Fehler

## Wie reproduziere ich den Bug
Schrittweise Anleitung:
1. Erstelle Konto
2. Nicht als Hauptkonto Setzen
3. Versuche Geld Einzuzahlen
4. See Error

## Was soll eigentlich passieren
Geld auf Konto

## Screenshots
Screenshots wenn es der Problem Lösung beiträgt

## Zusätzlicher Kontext
Weiterer Kontext

**Comment by XCOYoshi** [comment]
Eben so bei einem zweit Konto das nicht das Haupt Konto ist

**Comment by DELJN** [comment]
Fixed.
Ty an @ProfPanda07 für die genaue beschreibung.
