### ISSUE TITLE
Änderung Namen Justiz ränge

### ISSUE THREAD

**Issue by XCOYoshi** [Hydra-Roleplay/Issue-tracker#3]
ID | Name |
-------- | -------- | 
1   | Justiz Sicherheit| 
2 | Statsanwwalt/in in ausbildung| 
3   | Richter/in in ausbildung| 
4   | Statsanwwalt/in | 
5   | Richter/in   | 
6   | Oberster Statsanwwalt/in | 
7   | Oberster Richter/in |

**Comment by DELJN** [comment]
Fixed.
Danke @ProfPanda07 für den Issue
