### ISSUE TITLE
Banken auf der Map eingezeichnet wären nice

### ISSUE THREAD

**Issue by Velocina** [Hydra-Roleplay/Issue-tracker#6]
## Hat dein Fehler etwas mit einem Problem zutuen?
Ich habe keinen Orientierungssinn.

## Beschreibe dein Wunsch Lösung
Symbole für die Banken auf der Map. Ein Geldsymbol oder so.

## Alternative Lösungen die dir einfallen
Ein magischer Trank, der mir einen Orientierungssinn gibt. Idk

## Additional context
Fügen Sie hier weitere Informationen oder Screenshots zu Ihrer Anfrage hinzu.

**Comment by DELJN** [comment]
Mit nächstem Update kann man im Spieler Menu (taste M) die Blips ein bzw. ausschalten.
Standard sind alle an und ATM und Häuser wurden hinzugefügt.
