### ISSUE TITLE
Bei Auszahlung von Minijobs sagt der Server oben Rechts das man 0 erhält aber das Geld wird trotzdem überwiesen

### ISSUE THREAD

**Issue by ProfPanda07** [Hydra-Roleplay/Issue-tracker#9]
## Wie reproduziere ich den Bug
Schrittweise Anleitung:
1. Man macht Mini job
2. Mini Job sagt gibt kein Geld
3. See Error

**Comment by DELJN** [comment]
@ProfPanda07 Frage: welcher Minijob genau? Oder bei mehreren??

**Comment by DELJN** [comment]
Fixxed
